// ============================================
// 條文架構測驗題庫（共 100 題）
// answer：正確答案在 options 中的位置，從 0 開始算
// clause 開頭的數字會自動當作章節，用來分配抽題
// 「4～10」這類跨章題目會歸在「綜合」
// ============================================
const iso50001Questions = [

/* ========== 第4章 組織處境 ========== */
{ id: 1, clause: "4.1", clauseName: "瞭解組織及其處境",
  question: "組織建立能源管理系統時，首先應瞭解哪些可能影響能源管理系統預期結果的因素？",
  options: ["僅能源價格", "內部與外部議題", "僅政府法規", "僅設備使用年限"], answer: 1,
  explanation: "4.1要求組織確認與其目的相關，且可能影響能源管理系統及能源績效的內部與外部議題。" },
{ id: 2, clause: "4.1", clauseName: "瞭解組織及其處境",
  question: "下列何者最可能屬於影響能源管理系統的外部議題？",
  options: ["設備操作方式", "員工能源管理能力", "政府能源政策變化", "內部組織調整"], answer: 2,
  explanation: "政府政策、能源市場及外部環境變化均可能屬於外部議題。" },
{ id: 3, clause: "4.1", clauseName: "瞭解組織及其處境",
  question: "下列何者較可能屬於能源管理系統的內部議題？",
  options: ["國際能源價格", "政府能源政策", "廠內設備老舊", "國家能源法規"], answer: 2,
  explanation: "設備狀況、組織能力、內部資源等通常屬於內部議題。" },
{ id: 4, clause: "4.2", clauseName: "瞭解利害相關者的需求與期望",
  question: "組織應確認哪些利害相關者與能源管理系統有關，主要目的為何？",
  options: ["增加文件數量", "瞭解相關需求及要求", "決定設備品牌", "計算員工人數"], answer: 1,
  explanation: "應確認與EnMS及能源績效有關的利害相關者，以及其相關需求與期望。" },
{ id: 5, clause: "4.2", clauseName: "瞭解利害相關者的需求與期望",
  question: "下列何者可能是能源管理系統的利害相關者？",
  options: ["主管機關", "客戶", "能源供應商", "以上皆是"], answer: 3,
  explanation: "主管機關、客戶及能源供應商皆可能對組織能源管理產生相關要求。" },
{ id: 6, clause: "4.2", clauseName: "瞭解利害相關者的需求與期望",
  question: "組織對能源相關法令要求應採取何種作法？",
  options: ["只有驗證前確認", "確認並取得適用要求", "完全交由驗證公司判斷", "只有發生違規時處理"], answer: 1,
  explanation: "組織需確認與能源效率、能源使用及能源消耗相關的適用法令及其他要求。" },
{ id: 7, clause: "4.3", clauseName: "決定能源管理系統範疇",
  question: "決定能源管理系統範疇與邊界時，下列何者應納入考量？",
  options: ["內外部議題", "利害相關者相關要求", "組織可控制的活動與能源使用", "以上皆是"], answer: 3,
  explanation: "EnMS範疇需考量組織處境、相關要求以及組織對能源使用與能源績效的控制能力。" },
{ id: 8, clause: "4.3", clauseName: "決定能源管理系統範疇",
  question: "能源管理系統的範疇與邊界應如何處理？",
  options: ["只需口頭說明", "應予以建立並維持相關資訊", "完全由驗證機構決定", "每月重新制定"], answer: 1,
  explanation: "組織應確定EnMS的範疇及邊界，並維持其文件化資訊。" },
{ id: 9, clause: "4.3", clauseName: "決定能源管理系統範疇",
  question: "某工廠將高耗能製程任意排除在能源管理系統範圍之外，最可能涉及哪一條文？",
  options: ["4.3", "5.2", "7.2", "9.2"], answer: 0,
  explanation: "能源管理系統範疇及邊界的合理性屬於4.3要求。" },
{ id: 10, clause: "4.4", clauseName: "能源管理系統",
  question: "ISO 50001要求組織建立能源管理系統的核心目的之一為何？",
  options: ["增加程序文件", "持續改善能源績效", "增加設備數量", "降低員工人數"], answer: 1,
  explanation: "能源管理系統的重要目的之一是持續改善能源績效。" },

/* ========== 第5章 領導 ========== */
{ id: 11, clause: "5.1", clauseName: "領導與承諾",
  question: "能源管理系統最終的領導責任主要由誰承擔？",
  options: ["能源管理人員", "外部顧問", "最高管理階層", "驗證機構"], answer: 2,
  explanation: "最高管理階層須展現對能源管理系統及能源績效改善的領導與承諾。" },
{ id: 12, clause: "5.1", clauseName: "領導與承諾",
  question: "最高管理階層應確保能源管理系統所需資源如何取得？",
  options: ["只有驗證前提供", "依需求提供必要資源", "由員工自行負擔", "完全交由顧問處理"], answer: 1,
  explanation: "最高管理階層應確保建立、實施、維持及改善EnMS所需資源可以取得。" },
{ id: 13, clause: "5.1", clauseName: "領導與承諾",
  question: "下列何者最能展現最高管理階層對能源管理系統的承諾？",
  options: ["只在驗證當天參加會議", "確保能源政策、目標及資源與組織方向相符", "將所有工作交給能源管理人員", "只要求降低電費"], answer: 1,
  explanation: "領導與承諾包含確保能源政策、目標、資源及EnMS要求融入組織運作。" },
{ id: 14, clause: "5.1", clauseName: "領導與承諾",
  question: "能源績效改善是否僅為能源管理單位的責任？",
  options: ["是", "否", "僅大型企業不是", "標準沒有要求"], answer: 1,
  explanation: "最高管理階層需確保相關角色參與，能源績效改善並非單一部門責任。" },
{ id: 15, clause: "5.2", clauseName: "能源政策",
  question: "能源政策應由誰建立？",
  options: ["外部顧問", "驗證公司", "最高管理階層", "設備供應商"], answer: 2,
  explanation: "最高管理階層應建立能源政策。" },
{ id: 16, clause: "5.2", clauseName: "能源政策",
  question: "能源政策應包含對何者的承諾？",
  options: ["持續改善能源績效", "增加能源使用", "增加設備採購", "降低產品品質"], answer: 0,
  explanation: "能源政策需包含持續改善能源績效及EnMS的承諾。" },
{ id: 17, clause: "5.2", clauseName: "能源政策",
  question: "能源政策是否應支持能源效率產品與服務的採購？",
  options: ["是", "否", "只有政府機關需要", "只有能源供應商需要"], answer: 0,
  explanation: "能源政策應支持採購會影響能源績效的能源效率產品及服務。" },
{ id: 18, clause: "5.2", clauseName: "能源政策",
  question: "能源政策是否應支持考量能源績效改善的設計活動？",
  options: ["是", "否", "只有新建工廠需要", "只有ISO 14001要求"], answer: 0,
  explanation: "能源政策應支持考量能源績效改善的設計活動。" },
{ id: 19, clause: "5.3", clauseName: "組織角色、責任及職權",
  question: "能源管理系統相關角色的責任與職權應如何處理？",
  options: ["不需界定", "應予以指派並溝通", "全部由顧問負責", "全部由廠長負責"], answer: 1,
  explanation: "最高管理階層應確保相關角色的責任與職權被指派及溝通。" },
{ id: 20, clause: "5.3", clauseName: "組織角色、責任及職權",
  question: "誰應確保能源管理系統符合ISO 50001要求？",
  options: ["被指派具有相關責任與職權的人員", "客戶", "驗證機構", "能源供應商"], answer: 0,
  explanation: "最高管理階層應指派相關責任與職權，以確保EnMS符合標準要求。" },

/* ========== 第6章 規劃 ========== */
{ id: 21, clause: "6.1", clauseName: "處理風險與機會之措施",
  question: "能源管理系統規劃時，組織應確認什麼？",
  options: ["風險與機會", "只有財務風險", "只有設備故障", "只有能源價格"], answer: 0,
  explanation: "規劃EnMS時應確認需要處理的風險與機會。" },
{ id: 22, clause: "6.1", clauseName: "處理風險與機會之措施",
  question: "處理風險與機會的主要目的不包含下列何者？",
  options: ["確保EnMS達成預期結果", "防止或降低非預期影響", "達成持續改善", "增加能源消耗"], answer: 3,
  explanation: "風險與機會管理是為確保預期結果、降低不利影響並達成持續改善。" },
{ id: 23, clause: "6.2", clauseName: "目標、能源標的與達成之規劃",
  question: "能源目標與能源標的應與何者一致？",
  options: ["能源政策", "設備品牌", "員工人數", "驗證公司要求"], answer: 0,
  explanation: "能源目標及能源標的應與能源政策一致。" },
{ id: 24, clause: "6.2", clauseName: "目標、能源標的與達成之規劃",
  question: "設定能源目標與標的時，下列何者應納入考量？",
  options: ["重大能源使用", "改善能源績效的機會", "適用要求", "以上皆是"], answer: 3,
  explanation: "設定及審查能源目標標的時需考量適用要求、SEU及能源績效改善機會等。" },
{ id: 25, clause: "6.2", clauseName: "目標、能源標的與達成之規劃",
  question: "行動計畫中通常應明確規劃哪些內容？",
  options: ["執行事項、資源、責任、完成期限及結果評估方式", "只有預算", "只有負責人", "只有節電量"], answer: 0,
  explanation: "達成目標及標的的行動計畫應明確規劃執行事項、資源、責任、期限及結果評估方式。" },
{ id: 26, clause: "6.2", clauseName: "目標、能源標的與達成之規劃",
  question: "能源目標是否一定只能用kWh表示？",
  options: ["是", "否", "只有製造業可以", "只有服務業不需要"], answer: 1,
  explanation: "目標可依組織需求設定，不限定只能以單一能源單位表示。" },
{ id: 27, clause: "6.3", clauseName: "能源審查",
  question: "能源審查首先應分析何者？",
  options: ["能源使用與能源消耗", "員工薪資", "客戶滿意度", "產品售價"], answer: 0,
  explanation: "能源審查需分析能源使用及能源消耗相關資料。" },
{ id: 28, clause: "6.3", clauseName: "能源審查",
  question: "SEU是指什麼？",
  options: ["重大能源使用", "能源政策", "能源基線", "能源績效指標"], answer: 0,
  explanation: "SEU為Significant Energy Use，即重大能源使用。" },
{ id: 29, clause: "6.3", clauseName: "能源審查",
  question: "組織應依何種方式決定重大能源使用(SEU)？",
  options: ["隨機選擇", "依組織建立的準則判定", "全部設備皆必須列為SEU", "由驗證員指定"], answer: 1,
  explanation: "組織應建立適當準則，據以判定重大能源使用。" },
{ id: 30, clause: "6.3", clauseName: "能源審查",
  question: "針對重大能源使用，組織應確認下列何者？",
  options: ["相關變數", "目前能源績效", "影響或從事相關工作的人員", "以上皆是"], answer: 3,
  explanation: "SEU應確認相關變數、目前能源績效及影響SEU的人員等資訊。" },
{ id: 31, clause: "6.3", clauseName: "能源審查",
  question: "下列何者可能是空調系統的相關變數？",
  options: ["室外溫度", "員工姓名", "設備顏色", "公司成立日期"], answer: 0,
  explanation: "室外溫度可能直接影響空調能源使用，因此可能屬於相關變數。" },
{ id: 32, clause: "6.3", clauseName: "能源審查",
  question: "製造設備的能源使用與產量高度相關時，產量可能被視為什麼？",
  options: ["相關變數", "能源政策", "靜態因子", "矯正措施"], answer: 0,
  explanation: "會顯著影響能源績效且經常變動的因素，可作為相關變數。" },
{ id: 33, clause: "6.3", clauseName: "能源審查",
  question: "能源審查是否需要確認能源績效改善機會？",
  options: ["是", "否", "只有外部稽核時需要", "只有設備汰換時需要"], answer: 0,
  explanation: "能源審查需確認並排序能源績效改善機會。" },
{ id: 34, clause: "6.3", clauseName: "能源審查",
  question: "能源審查是否需要估計未來能源使用與能源消耗？",
  options: ["是", "否", "只有新工廠需要", "只有上市公司需要"], answer: 0,
  explanation: "能源審查包含估計未來能源使用及能源消耗。" },
{ id: 35, clause: "6.3", clauseName: "能源審查",
  question: "當設備、設施或能源系統發生重大變更時，能源審查應如何處理？",
  options: ["不需處理", "視需要更新能源審查", "五年後再更新", "只通知驗證公司"], answer: 1,
  explanation: "能源審查應依規劃期間更新，重大設施、設備、系統或製程變更時也應適時更新。" },
{ id: 36, clause: "6.4", clauseName: "能源績效指標",
  question: "EnPI是指什麼？",
  options: ["能源績效指標", "能源基線", "能源政策", "能源審查"], answer: 0,
  explanation: "EnPI為Energy Performance Indicator，即能源績效指標。" },
{ id: 37, clause: "6.4", clauseName: "能源績效指標",
  question: "EnPI主要用途為何？",
  options: ["衡量與監控能源績效", "計算員工績效", "管理產品品質", "計算營業收入"], answer: 0,
  explanation: "EnPI用於衡量及監控組織的能源績效。" },
{ id: 38, clause: "6.4", clauseName: "能源績效指標",
  question: "下列何者最可能作為製造業的EnPI？",
  options: ["kWh/產品產量", "員工姓名", "公司地址", "產品售價"], answer: 0,
  explanation: "單位產量能源使用量是常見的能源績效指標。" },
{ id: 39, clause: "6.4", clauseName: "能源績效指標",
  question: "當相關變數顯著影響能源績效時，建立EnPI應如何處理？",
  options: ["忽略相關變數", "適當考量相關變數", "刪除EnPI", "停止能源管理"], answer: 1,
  explanation: "若相關變數顯著影響能源績效，建立適當EnPI時應考量相關資料。" },
{ id: 40, clause: "6.4", clauseName: "能源績效指標",
  question: "EnPI值通常應與何者進行比較？",
  options: ["能源基線(EnB)", "能源政策", "內部稽核報告", "組織架構圖"], answer: 0,
  explanation: "EnPI值應依適當情況與其對應的能源基線進行比較。" },
{ id: 41, clause: "6.5", clauseName: "能源基線",
  question: "EnB代表什麼？",
  options: ["能源基線", "能源績效指標", "重大能源使用", "能源政策"], answer: 0,
  explanation: "EnB為Energy Baseline，即能源基線。" },
{ id: 42, clause: "6.5", clauseName: "能源基線",
  question: "能源基線主要依據何者建立？",
  options: ["能源審查資訊", "員工意見", "驗證公司建議", "設備供應商報價"], answer: 0,
  explanation: "能源基線應利用能源審查所得資訊並選擇適當期間建立。" },
{ id: 43, clause: "6.5", clauseName: "能源基線",
  question: "當相關變數顯著影響能源績效時，EnPI及EnB可能需要進行什麼處理？",
  options: ["正規化", "刪除", "停止量測", "改成能源政策"], answer: 0,
  explanation: "相關變數顯著影響能源績效時，應依需要進行正規化。" },
{ id: 44, clause: "6.5", clauseName: "能源基線",
  question: "下列何種情況可能需要調整能源基線？",
  options: ["EnPI已無法反映能源績效", "靜態因子發生重大改變", "依預先決定的方法需要調整", "以上皆是"], answer: 3,
  explanation: "ISO 50001規定上述情況均可能需要修訂EnB。" },
{ id: 45, clause: "6.5", clauseName: "能源基線",
  question: "工廠新增一條大型生產線，使能源使用型態發生重大改變，最可能需要重新檢討何者？",
  options: ["能源基線", "員工制服", "客戶名單", "公司名稱"], answer: 0,
  explanation: "重大靜態因子改變可能使原能源基線不再適用。" },
{ id: 46, clause: "6.6", clauseName: "能源資料蒐集規劃",
  question: "能源資料蒐集計畫應與哪些條件相適應？",
  options: ["組織規模", "複雜程度及資源", "量測與監控設備", "以上皆是"], answer: 3,
  explanation: "資料蒐集計畫應依組織規模、複雜度、資源及量測設備等條件規劃。" },
{ id: 47, clause: "6.6", clauseName: "能源資料蒐集規劃",
  question: "能源資料蒐集計畫應說明什麼？",
  options: ["需要蒐集的資料及蒐集頻率", "員工薪資", "公司營業額", "客戶數量"], answer: 0,
  explanation: "資料蒐集計畫應界定必要資料，以及如何與多常蒐集及保存資料。" },
{ id: 48, clause: "6.6", clauseName: "能源資料蒐集規劃",
  question: "下列何者屬於應考量蒐集的能源資料？",
  options: ["SEU相關變數", "SEU能源消耗", "SEU操作準則", "以上皆是"], answer: 3,
  explanation: "SEU相關變數、能源消耗及操作準則均屬重要能源資料。" },
{ id: 49, clause: "6.6", clauseName: "能源資料蒐集規劃",
  question: "若適用，能源資料蒐集內容還應包含下列何者？",
  options: ["靜態因子", "員工生日", "客戶地址", "公司Logo"], answer: 0,
  explanation: "若適用，資料蒐集應包含影響能源績效的靜態因子。" },
{ id: 50, clause: "6.6", clauseName: "能源資料蒐集規劃",
  question: "用於量測能源績效關鍵特性的設備，應特別注意什麼？",
  options: ["外觀漂亮", "資料準確性與重複性", "品牌相同", "價格最高"], answer: 1,
  explanation: "組織應確保相關量測設備提供適當準確且可重複的資料。" },

/* ========== 第7章 支援 ========== */
{ id: 51, clause: "7.1", clauseName: "資源",
  question: "組織應提供哪些資源以建立及改善能源管理系統？",
  options: ["必要的人力與相關資源", "只有財務資源", "只有外部顧問", "不需要資源"], answer: 0,
  explanation: "組織需決定並提供建立、實施、維持及持續改善EnMS所需資源。" },
{ id: 52, clause: "7.2", clauseName: "能力",
  question: "對影響能源績效及EnMS的人員，組織應確保其具備什麼？",
  options: ["適當能力", "高學歷", "十年以上年資", "主管職位"], answer: 0,
  explanation: "組織應確保相關人員依教育、訓練、技能或經驗具備必要能力。" },
{ id: 53, clause: "7.2", clauseName: "能力",
  question: "若發現人員能力不足，組織較適當的作法為何？",
  options: ["不處理", "採取訓練或其他措施取得所需能力", "直接停止EnMS", "等外部稽核再處理"], answer: 1,
  explanation: "組織需採取措施取得必要能力，並評估所採措施的有效性。" },
{ id: 54, clause: "7.2", clauseName: "能力",
  question: "能力證明是否可以包含教育、訓練、技能或經驗？",
  options: ["是", "否", "只能用證照", "只能用學歷"], answer: 0,
  explanation: "人員能力可依適當教育、訓練、技能或經驗加以證明。" },
{ id: 55, clause: "7.3", clauseName: "認知",
  question: "相關人員應瞭解下列何者？",
  options: ["能源政策", "自身對EnMS有效性的貢獻", "不符合要求可能造成的影響", "以上皆是"], answer: 3,
  explanation: "認知要求包含能源政策、個人貢獻及未符合要求可能造成的影響。" },
{ id: 56, clause: "7.3", clauseName: "認知",
  question: "員工是否應瞭解其活動如何影響能源績效？",
  options: ["是", "否", "只有主管需要", "只有能源管理人員需要"], answer: 0,
  explanation: "從事影響能源績效工作的人員應具有相應的能源績效認知。" },
{ id: 57, clause: "7.4", clauseName: "溝通",
  question: "組織建立能源管理溝通機制時，應決定什麼？",
  options: ["溝通什麼", "何時及與誰溝通", "如何溝通", "以上皆是"], answer: 3,
  explanation: "溝通規劃應界定溝通內容、時間、對象及方式等。" },
{ id: 58, clause: "7.4", clauseName: "溝通",
  question: "能源管理相關溝通是否只有對內溝通？",
  options: ["是", "否，依需求包含內部與外部溝通", "只有外部", "標準禁止外部溝通"], answer: 1,
  explanation: "組織應依EnMS需求建立內部及外部溝通安排。" },
{ id: 59, clause: "7.5", clauseName: "文件化資訊",
  question: "能源管理系統文件化資訊主要包含哪些？",
  options: ["標準要求的文件化資訊", "組織認為EnMS有效運作所需資訊", "以上皆是", "只有能源手冊"], answer: 2,
  explanation: "文件化資訊包含標準要求及組織認為EnMS有效性所需的資訊。" },
{ id: 60, clause: "7.5", clauseName: "文件化資訊",
  question: "建立或更新文件時，應適當考量什麼？",
  options: ["識別與描述", "格式與媒介", "審查及核准", "以上皆是"], answer: 3,
  explanation: "文件建立及更新應適當控制識別、格式、媒介、審查及核准等事項。" },
{ id: 61, clause: "7.5", clauseName: "文件化資訊",
  question: "文件化資訊是否一定只能使用紙本？",
  options: ["是", "否", "只有紀錄可以電子化", "只有程序書可以電子化"], answer: 1,
  explanation: "文件化資訊可採各種適當媒介，不限於紙本。" },
{ id: 62, clause: "7.5", clauseName: "文件化資訊",
  question: "對外來文件，如法規或設備操作手冊，若為EnMS運作所需，應如何處理？",
  options: ["不需管理", "適當識別並控制", "全部銷毀", "只由顧問保管"], answer: 1,
  explanation: "EnMS規劃及運作所需的外部來源文件化資訊應適當識別並受到控制。" },

/* ========== 第8章 運作 ========== */
{ id: 63, clause: "8.1", clauseName: "運作規劃與管制",
  question: "組織對重大能源使用相關作業應採取何種方式？",
  options: ["依建立的準則進行運作與管制", "完全自由操作", "只有稽核前控制", "不需設定任何條件"], answer: 0,
  explanation: "與SEU及能源績效相關的作業應建立適當準則並依其實施控制。" },
{ id: 64, clause: "8.1", clauseName: "運作規劃與管制",
  question: "操作準則的主要目的之一為何？",
  options: ["避免重大偏離預期能源績效", "增加能源使用", "增加文件", "降低產品品質"], answer: 0,
  explanation: "適當的運作準則可避免因缺乏控制造成能源績效的重大偏離。" },
{ id: 65, clause: "8.1", clauseName: "運作規劃與管制",
  question: "重大能源使用設備的操作條件應如何管理？",
  options: ["建立並實施適當操作準則", "由操作員自行決定", "不需管理", "只需記錄設備名稱"], answer: 0,
  explanation: "SEU相關運作應依適當操作及維護準則進行控制。" },
{ id: 66, clause: "8.1", clauseName: "運作規劃與管制",
  question: "組織外包與重大能源使用相關的製程時，是否仍需考量控制？",
  options: ["是", "否", "完全由承包商負責", "只有政府要求時需要"], answer: 0,
  explanation: "外包過程若與SEU或能源績效有關，仍應確保受到適當控制。" },
{ id: 67, clause: "8.2", clauseName: "設計",
  question: "設計新的設施、設備、系統或能源使用製程時，何時應考量能源績效改善機會？",
  options: ["設計階段", "設備報廢後", "驗證完成後", "完全不需要"], answer: 0,
  explanation: "對預期在使用期間可能顯著影響能源績效的設計活動，應考量能源績效改善機會。" },
{ id: 68, clause: "8.2", clauseName: "設計",
  question: "設計活動的能源績效評估結果應如何處理？",
  options: ["適當納入設計活動", "完全忽略", "只口頭告知", "驗證後再考慮"], answer: 0,
  explanation: "能源績效評估結果應適當納入相關設計、規格及採購活動。" },
{ id: 69, clause: "8.3", clauseName: "採購",
  question: "採購預期會對能源績效產生重大影響的設備時，應考量什麼？",
  options: ["能源績效", "能源使用與消耗", "使用期間的能源表現", "以上皆是"], answer: 3,
  explanation: "採購重大能源使用相關產品、設備及服務時應評估能源績效相關因素。" },
{ id: 70, clause: "8.3", clauseName: "採購",
  question: "組織是否應將能源績效相關採購要求適當傳達給供應商？",
  options: ["是", "否", "只有國營企業需要", "只有設備超過一定金額才需要"], answer: 0,
  explanation: "對可能影響SEU的採購，應適當告知供應商能源績效相關要求。" },
{ id: 71, clause: "8.3", clauseName: "採購",
  question: "採購能源時，組織是否可以建立能源採購規格？",
  options: ["是", "否", "ISO 50001禁止", "只能由政府制定"], answer: 0,
  explanation: "組織應依適用情況建立及實施能源採購相關規格。" },

/* ========== 第9章 績效評估 ========== */
{ id: 72, clause: "9.1", clauseName: "監督、量測、分析與評估",
  question: "組織應定期監督及量測什麼？",
  options: ["影響能源績效的關鍵特性", "只有員工出勤", "只有營業收入", "只有產品產量"], answer: 0,
  explanation: "應依規劃期間監督、量測、分析及評估能源績效及EnMS。" },
{ id: 73, clause: "9.1", clauseName: "監督、量測、分析與評估",
  question: "下列何者可能屬於能源績效的關鍵特性？",
  options: ["重大能源使用", "EnPI", "行動計畫成效", "以上皆是"], answer: 3,
  explanation: "SEU、EnPI及行動計畫成效等皆可能屬於需監督分析的重要內容。" },
{ id: 74, clause: "9.1", clauseName: "監督、量測、分析與評估",
  question: "實際能源消耗與預期相比出現重大偏差時，組織應如何處理？",
  options: ["忽略", "調查並適當回應", "刪除數據", "修改能源政策即可"], answer: 1,
  explanation: "能源績效發生重大偏差時應進行調查及適當回應。" },
{ id: 75, clause: "9.1", clauseName: "監督、量測、分析與評估",
  question: "能源績效改善通常可透過何者判斷？",
  options: ["比較EnPI與EnB", "比較員工人數", "比較產品售價", "比較公司Logo"], answer: 0,
  explanation: "能源績效改善通常透過EnPI值與適當能源基線進行比較及評估。" },
{ id: 76, clause: "9.1", clauseName: "監督、量測、分析與評估",
  question: "組織是否應定期評估適用法令及其他要求的符合情形？",
  options: ["是", "否", "只有發生違規時", "只有驗證前"], answer: 0,
  explanation: "組織需依規劃期間評估能源相關法令及其他要求的符合情形。" },
{ id: 77, clause: "9.1", clauseName: "監督、量測、分析與評估",
  question: "監督與量測結果是否需要保留適當的文件化資訊？",
  options: ["是", "否", "只有異常才需要", "只有外部稽核資料需要"], answer: 0,
  explanation: "組織需保留適當文件化資訊作為監督、量測、分析及評估結果的證據。" },
{ id: 78, clause: "9.2", clauseName: "內部稽核",
  question: "內部稽核的主要目的之一為何？",
  options: ["確認EnMS是否符合組織自身及ISO 50001要求", "計算員工薪資", "決定設備採購品牌", "增加文件數量"], answer: 0,
  explanation: "內部稽核需確認EnMS是否符合組織自身要求及標準要求，並有效實施與維持。" },
{ id: 79, clause: "9.2", clauseName: "內部稽核",
  question: "內部稽核是否需要依規劃的時間間隔執行？",
  options: ["是", "否", "只有驗證前", "每十年一次即可"], answer: 0,
  explanation: "組織應依規劃的時間間隔執行內部稽核。" },
{ id: 80, clause: "9.2", clauseName: "內部稽核",
  question: "規劃內部稽核方案時應考量什麼？",
  options: ["相關過程的重要性", "影響能源績效的過程", "前次稽核結果", "以上皆是"], answer: 3,
  explanation: "稽核方案應考量相關過程的重要性、能源績效影響及先前稽核結果。" },
{ id: 81, clause: "9.2", clauseName: "內部稽核",
  question: "選擇內部稽核員時，應特別確保什麼？",
  options: ["稽核過程的客觀性與公正性", "一定是最高主管", "一定是外部人員", "一定具有十年經驗"], answer: 0,
  explanation: "稽核員選擇及稽核執行需確保稽核過程客觀及公正。" },
{ id: 82, clause: "9.2", clauseName: "內部稽核",
  question: "內部稽核結果應向誰報告？",
  options: ["相關管理階層", "只有外部顧問", "只有設備商", "不需報告"], answer: 0,
  explanation: "內部稽核結果應向相關管理階層報告。" },
{ id: 83, clause: "9.2", clauseName: "內部稽核",
  question: "內部稽核發現不符合事項後，組織應如何處理？",
  options: ["採取適當矯正與矯正措施", "直接刪除稽核紀錄", "等待下次驗證", "不需處理"], answer: 0,
  explanation: "稽核發現的問題應依適當程序進行矯正及矯正措施。" },
{ id: 84, clause: "9.3", clauseName: "管理審查",
  question: "管理審查應由誰執行？",
  options: ["最高管理階層", "設備供應商", "驗證機構", "客戶"], answer: 0,
  explanation: "最高管理階層應依規劃期間審查能源管理系統。" },
{ id: 85, clause: "9.3", clauseName: "管理審查",
  question: "管理審查的主要目的為何？",
  options: ["確認EnMS持續適用、充分、有效並與策略方向一致", "只確認電費", "只確認設備數量", "只確認稽核日期"], answer: 0,
  explanation: "管理審查用以確認EnMS持續的適用性、充分性及有效性等。" },
{ id: 86, clause: "9.3", clauseName: "管理審查",
  question: "管理審查輸入應包含下列何者？",
  options: ["先前管理審查措施的追蹤", "能源績效資訊", "內部稽核結果", "以上皆是"], answer: 3,
  explanation: "上述項目均屬管理審查常見且重要的輸入內容。" },
{ id: 87, clause: "9.3", clauseName: "管理審查",
  question: "管理審查是否應檢討能源政策？",
  options: ["是", "否", "只有第一次導入需要", "只有政策違反法規時"], answer: 0,
  explanation: "管理審查需適當檢討能源政策。" },
{ id: 88, clause: "9.3", clauseName: "管理審查",
  question: "管理審查是否應檢討能源目標與標的達成程度？",
  options: ["是", "否", "只有未達成才需要", "只有外部驗證時需要"], answer: 0,
  explanation: "目標與能源標的達成程度屬管理審查的重要資訊。" },
{ id: 89, clause: "9.3", clauseName: "管理審查",
  question: "下列何者可能屬於管理審查輸出？",
  options: ["持續改善機會的決定", "EnMS變更需求", "資源需求", "以上皆是"], answer: 3,
  explanation: "管理審查輸出應反映改善機會、系統變更及資源等相關決定。" },
{ id: 90, clause: "9.3", clauseName: "管理審查",
  question: "管理審查結果是否應保留文件化資訊？",
  options: ["是", "否", "只有驗證當年", "只有不符合時"], answer: 0,
  explanation: "管理審查結果需保留適當文件化資訊作為執行證據。" },

/* ========== 第10章 改善 ========== */
{ id: 91, clause: "10.1", clauseName: "不符合事項與矯正措施",
  question: "發生不符合事項時，組織首先應如何處理？",
  options: ["對不符合事項作出反應並適當控制與矯正", "刪除紀錄", "等待驗證機構處理", "完全忽略"], answer: 0,
  explanation: "發生不符合事項時應及時反應，進行控制、矯正並處理相關後果。" },
{ id: 92, clause: "10.1", clauseName: "不符合事項與矯正措施",
  question: "矯正措施的重要目的之一為何？",
  options: ["消除不符合原因，避免再次發生", "增加文件", "增加能源使用", "隱藏問題"], answer: 0,
  explanation: "矯正措施重點在處理造成不符合的原因，以避免再次發生或於其他地方發生。" },
{ id: 93, clause: "10.1", clauseName: "不符合事項與矯正措施",
  question: "進行矯正措施前，通常需要評估什麼？",
  options: ["不符合原因", "是否存在類似問題", "是否可能在其他地方發生", "以上皆是"], answer: 3,
  explanation: "需分析原因並確認是否存在或可能發生類似不符合。" },
{ id: 94, clause: "10.1", clauseName: "不符合事項與矯正措施",
  question: "完成矯正措施後，是否應審查措施有效性？",
  options: ["是", "否", "只有重大缺失需要", "只有外部稽核要求才需要"], answer: 0,
  explanation: "組織應審查所採矯正措施的有效性。" },
{ id: 95, clause: "10.1", clauseName: "不符合事項與矯正措施",
  question: "矯正措施是否應與不符合事項造成的影響程度相適應？",
  options: ["是", "否", "所有問題都使用相同措施", "標準未涉及"], answer: 0,
  explanation: "矯正措施應與所遭遇不符合的影響程度相適應。" },
{ id: 96, clause: "10.2", clauseName: "持續改善",
  question: "ISO 50001要求組織持續改善什麼？",
  options: ["能源管理系統的適用性、充分性及有效性", "只有文件數量", "只有設備數量", "只有員工人數"], answer: 0,
  explanation: "組織需持續改善EnMS的適用性、充分性及有效性。" },
{ id: 97, clause: "10.2", clauseName: "持續改善",
  question: "ISO 50001除了改善管理系統外，還特別要求持續改善何者？",
  options: ["能源績效", "員工數量", "產品種類", "公司規模"], answer: 0,
  explanation: "持續改善能源績效是ISO 50001的核心要求之一。" },

/* ========== 綜合題 ========== */
{ id: 98, clause: "6.3 / 6.4 / 6.5", clauseName: "能源審查、EnPI與EnB",
  question: "下列哪一個邏輯順序最符合能源績效管理概念？",
  options: ["能源審查 → 確認SEU → 建立EnPI → 建立EnB → 評估能源績效", "EnB → 能源政策 → SEU → 稽核", "內部稽核 → EnPI → 能源審查", "管理審查 → EnB → 能源政策"], answer: 0,
  explanation: "能源審查提供建立SEU、EnPI及EnB的重要基礎資訊，之後才能進一步評估能源績效。" },
{ id: 99, clause: "4～10", clauseName: "PDCA架構",
  question: "ISO 50001採用何種管理循環概念推動能源管理系統持續改善？",
  options: ["PDCA", "SWOT", "5S", "FIFO"], answer: 0,
  explanation: "ISO 50001能源管理系統以PDCA持續改善概念運作。" },
{ id: 100, clause: "4～10", clauseName: "整體條文架構",
  question: "下列哪一組最能代表ISO 50001:2018第4至10章的主要架構？",
  options: ["組織處境、領導、規劃、支援、運作、績效評估、改善", "採購、生產、銷售、財務、人資", "品質、環境、安全、財務、資訊", "設備、產品、客戶、供應商、員工"], answer: 0,
  explanation: "ISO 50001:2018第4至10章依序涵蓋組織處境、領導、規劃、支援、運作、績效評估及改善。" }

];
